### ISSUE TITLE
Third party authentication

### ISSUE THREAD

**Issue by WillTheDeveloper** [Study-Portal/roadmap#12]
# Summary

I can't imagine a lot of people using it but third party app support for authentication should be implemented to allow them to sign up and sign in with third party applications such as GitHub. Not sure why but I would imagine some users find this easy because they don't need to enter their details all over again.

# Expected outcome

- [ ] [Google](https://socialiteproviders.com/Google-Plus/)
- [x] [GitHub](https://socialiteproviders.com/GitHub/) (*Q1 has a simple functionality of this but is hidden from frontend*)
- [ ] [Spotify](https://socialiteproviders.com/Spotify/)
- [ ] [Microsoft account](https://socialiteproviders.com/Microsoft/)

**Comment by pussy-cats** [comment]
> @pussy-cats Just so you know, Socialite is already installed. Just added links to all the guides.

Yup. Reinstalling my Hackintosh for now as My Dev Environment is broken hoho. What do you use for Dev Environment?

**Comment by WillTheDeveloper** [comment]
@pussy-cats I used Ubuntu for a long while but now I use Windows all the time.

**Comment by WillTheDeveloper** [comment]
@pussy-cats You still working on this or nah?

**Comment by WillTheDeveloper** [comment]
Reopen this when you return to it.
