### ISSUE TITLE
Clean up the design of the home pages

### ISSUE THREAD

**Issue by WillTheDeveloper** [Study-Portal/roadmap#18]
# Summary

The main pages have been redesigned a few times prior to release but there are a few areas that need cleaning up regarding the text colour and content of the pages.

This covers the following pages:

- Home
- Features
- Pricing
- Contact

# Expected outcome

- [ ] Clean up the home page
- [ ] Clean up the features page
- [ ] Clean up the pricing page
- [ ] Clean up the contact page

**Comment by mauro-balades** [comment]
what do you mean with cleanup?

**Comment by WillTheDeveloper** [comment]
Kinda like, adjust some things. Sorry the wording is bad. For example, some text is hard to read because its grey on grey which obviously needs fixing. @mauro-balades

**Comment by mauro-balades** [comment]
the color gradient is still on...

**Comment by WillTheDeveloper** [comment]
Yeah I know. I don't think its that baddddddddd. Is that that bad?

**Comment by mauro-balades** [comment]
idk, it is not the theme of the website + some text is hard to read

**Comment by WillTheDeveloper** [comment]
Fair enough. I am not great with colours and stuff. The text colour can be changed really easily. Do you have any better colour scheming ideas 🤔

**Comment by mauro-balades** [comment]
I would say to keep it simple and just have it gray. If you want, you can also change the gray background for some other section but not in a gradient (linear gradients are from the 90's).

but u r the boss, so u decide
